# Generated by Django 4.1.2 on 2022-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplemodel",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
