# Generated by Django 4.1.2 on 2023-02-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
